sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUD_SDK_CORE_DISABLE_PROMPTS=1
before_install:
  # encryp tservice_account.json
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-acount --key-file service.account.json
  - glcoud config set project ID_FOR_PROJECT_NAME_ON_GLCOUD
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get credentials NAME_CLUSTER
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t bog754/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bog754/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
