apiVersion: skaffold/v2beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: bog754/fibo-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
deploy:
  kubectl:
    manifests:
      - k8s/client-deployement.yaml
